version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8

aliases:
  - &step_migrate
    name: Database migration
    command: |
      heroku run make heroku-migrate --app $HEROKU_APP_NAME

workflows:
  build-and-deploy:
    jobs:
      - build
      # - stage-deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: stage
      # - prod-deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master

jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
          DATABASE_URL: postgres://postgres@localhost:5432/real_estate_test
      - image: mdillon/postgis:11-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: real_estate_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - deps-
      - run:
          name: Upgrade poetry
          command: |
            pip install --user poetry==1.0.0
      - run:
          name: Install dependencies
          command: |
            make install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run linter
          command: |
            make lint
      - run:
          name: Wait for db
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run the Tests
          command: |
            make test
      - store_artifacts:
          path: test-reports/
      - store_test_results:
          path: test-reports/

  stage-deploy:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: "real-estate-prices-api-stage"
    steps:
      - checkout
      - heroku/deploy-via-git:
          only-branch: stage
      - heroku/install
      - run: *step_migrate

  prod-deploy:
    executor: heroku/default
    environment:
      HEROKU_APP_NAME: "real-estate-prices-api"
    steps:
      - checkout
      - heroku/deploy-via-git:
          only-branch: master
      - heroku/install
      - run: *step_migrate
