"""empty message

Revision ID: 579556f7500b
Revises: 71f6d75c08cb
Create Date: 2019-08-31 16:21:18.192808

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "579556f7500b"
down_revision = "71f6d75c08cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("locations_places_id_key", "locations", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("locations_places_id_key", "locations", ["places_id"])
    # ### end Alembic commands ###
