"""empty message

Revision ID: 579556f7500b
Revises: 71f6d75c08cb
Create Date: 2019-08-31 16:21:18.192808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "579556f7500b"
down_revision = "71f6d75c08cb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("locations_places_id_key", "locations", type_="unique")
    op.create_index("area_price_index", "properties", ["area", "price"], unique=False)
    op.add_column("properties", sa.Column("url", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("locations_places_id_key", "locations", ["places_id"])
    op.drop_index("area_price_index", table_name="properties")
    op.drop_column("properties", "url")
    # ### end Alembic commands ###
