"""empty message

Revision ID: 71f6d75c08cb
Revises: 0f82a9aaafa1
Create Date: 2019-08-25 17:32:29.001065

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "71f6d75c08cb"
down_revision = "0f82a9aaafa1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "locations", ["postal_code"])
    op.create_unique_constraint(None, "locations", ["places_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "locations", type_="unique")
    op.drop_constraint(None, "locations", type_="unique")
    # ### end Alembic commands ###
