"""empty message

Revision ID: c18de4cac5ad
Revises:
Create Date: 2019-12-15 12:29:08.360854

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = "c18de4cac5ad"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federal_unity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("short_name", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("federal_unity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["federal_unity_id"], ["federal_unity.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "neighbourhood",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["city.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "street",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("postal_code", sa.String(length=9), nullable=False),
        sa.Column("neighbourhood_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["neighbourhood_id"], ["neighbourhood.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("postal_code"),
    )
    op.create_table(
        "location",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geom", geoalchemy2.types.Geometry(geometry_type="POINT"), nullable=False
        ),
        sa.Column("places_id", sa.String(), nullable=False),
        sa.Column("street_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["street_id"], ["street.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "properties",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("area", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("properties")
    op.drop_table("location")
    op.drop_table("street")
    op.drop_table("neighbourhood")
    op.drop_table("city")
    op.drop_table("federal_unity")
    # ### end Alembic commands ###
